gestionplanning/gestionplanning/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib import admin
from django.urls import path

import planning.views

urlpatterns = [
    path('planning/', include('planning.urls')),
    path('admin/', admin.site.urls),
    path('', planning.views.login_page, name='login'),
    path('logout/', planning.views.logout_user, name='logout'),
]

gestionplanning/planning/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('index', views.index, name='index'),
]

gestionplanning/planning/models.py
import datetime

from django.db import models


# Create your models here.

# Models Adherent regroupe les information nécessaire pour un adhérent
class Adherent(models.Model):
    Prenom = models.CharField(max_length=50)
    Nom = models.CharField(max_length=50)
    Adresse_Rue = models.CharField(max_length=50)
    Adresse_CP = models.CharField(max_length=50)
    Adresse_Ville = models.CharField(max_length=50)
    Telephone = models.CharField(blank=False, max_length=10)
    Mail = models.CharField(max_length=50)
    Genre = models.CharField(max_length=50)
    Niveau = models.CharField(max_length=20)
    Numero_Licence = models.CharField(max_length=20)
    Date_Naissance = models.DateTimeField()
    Certificat_Medical = models.CharField(max_length=50)
    Date_Certificat = models.DateTimeField()
    Pointure = models.CharField(max_length=50)
    Taille = models.CharField(max_length=50)
    Date_inscription = models.DateTimeField()

    def __str__(self):
        return self.Nom + self.Prenom


# Models Entraineur  hérite de Adhérent, un entraineur est forcément un adhérent

class Entraineur(models.Model):
    adherent = models.OneToOneField(
        Adherent, on_delete=models.CASCADE, related_name="entraineur", primary_key=True,
    )

    def __str__(self):
        return self.adherent.Nom + self.adherent.Prenom


# Models Coach  hérite de Entraineur, un coach est forcément un entraineur

class Coach(models.Model):
    entraineur = models.OneToOneField(
        Entraineur, on_delete=models.CASCADE, primary_key=True,
    )

    def __str__(self):
        return self.entraineur.adherent.Nom + self.entraineur.adherent.Prenom


# Models Entrainement regroupe les information nécessaire pour un entrainement

class Entrainement(models.Model):
    Dates = models.DateTimeField()
    Lien_fichier = models.CharField(max_length=300)
    entraineurs = models.ManyToManyField(Entraineur)
    coach = models.ForeignKey(Coach, related_name="coachs_entrainement", on_delete=models.CASCADE)

    # Models Role, contient les différent role occupé par des adhérent dans l'association, différent des groupes


class Role(models.Model):
    Nom = models.CharField(max_length=50)
    adherents = models.ManyToManyField(Adherent)

    def __str__(self):
        return self.Nom

gestionplanning/planning/views.py
from django.contrib.auth import login, authenticate, logout
from .models import Adherent, Entrainement
from django.shortcuts import redirect
from . import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render



# Procédure de logout qui permet de déconnecter un utilisateur du site et redirige vers la page login


# Views Login, permet la connexion d'un utilisateur a condition qu'il ai été créé.
def login_page(request):
    form = forms.LoginForm()
    message = ''
    adherents = Adherent.objects.all()
    # Lorsque l'utilsateur clique sur ce connecter les donné vont être envoyer
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)  # On récupère les donnée du formulaire
        # On valide les données du formulaire avec le is_valid()
        if form.is_valid():
            # authneticate() permet de vérifier si l'username et password existe bien.
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            # Si l'username et le password sont bon on passe a la connexion
            if user is not None:
                # La fonction Login() gère la connexion
                login(request, user)
                return HttpResponseRedirect('/planning/index')

            else:
                message = 'Un problème est survenu veuillez vous reconnecter .'
    return render(
        request, 'planning/login.html', context={'form': form, 'message': message, 'adherents': adherents})


def logout_user(request):
    logout(request)
    return redirect('login')


def index(request):
    adherents = Adherent.objects.all()
    entrainements = Entrainement.objects.all()
    return render(request, 'planning/index.html', {'adherents': adherents, 'entrainements': entrainements})

gestionplanning/planning/templates/planning/index.html
<!doctype html>
{% load static %}
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Titre de la page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'planning/style.css' %}">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card mt-5">
                <div class="card-body">
                <h1 class="h1 text-center"> Voici la liste des entrainements : </h1>
                {% for entrainement in entrainements %}
                     <h1 class="h2">{{ entrainement.Dates }}</h1>
                        <h2 class="h3">Les entraineurs  </h2>
                     <ul>
                        <li>{{ entrainement.entraineurs.all|join:", " }}</li>
                     </ul>
                {%  endfor %}
              <p class ="mt-4"> Si vous souhaitez déclarer un annulation ou une possibilité d'échange cliquer sur le mail : <a href="mailto:meguenani.mehdi@gmail.com"> meguenani.mehdi@gmail.com</a></p>

              <a class="button mt-3" href="{% url 'logout' %}">Se déconnecter</a></p>
                </div>
                </div>
            </div>
        </div>
        {% if perms.planning.add_entrainement %}
        <div class="card mt-5">
            <div class="card-body">
              <a href="/admin/planning/entrainement/add/"><button class="button"> Cliquer ici pour ajouter un entrainement </button></a>
              <a href="/admin/planning/entrainement"><button class="button"> Cliquer ici pour modifier un entrainement </button></a>
            </div>
        </div>
        {% endif %}

    </div>
</body>
</html>

gestionplanning/planning/templates/planning/login.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-info text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>
            <form method="post">

              <div class="form-outline form-white mb-4">
            {{ form.as_p }}
            {% csrf_token %}
              </div>
              <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>